#! /bin/sh


bspc monitor -d I II III IV eI eII eIII eIV Music
# bspc monitor east -d eI eII eIII eIV eV

bspc config border_width                  2
bspc config window_gap                    32
bspc config split_ratio      	            0.5
bspc config borderless_monocle	          true
bspc config gapless_monocle	              false
bspc config click_to_focus	              true

bspc config remove_disabled_monitors      false
bspc config remove_unplugged_monitors     false
bspc config merge_overlapping_monitors    true

bspc config external_rules_command $HOME/.config/bspwm/external_rules

## My Colours ##
source "$HOME/.start-bspwm"
bspc config active_border_color	 	$(xrdb -get theme.background)
bspc config focused_border_color 	$(xrdb -get theme.background-alt)
bspc config normal_border_color		$(xrdb -get theme.background)
bspc config presel_border_color		$(xrdb -get theme.primary)
bspc config urgent_border_color		$(xrdb -get theme.danger)

