#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII Music

bspc config border_width         2
bspc config window_gap          32

bspc config split_ratio      	0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	false
bspc config click_to_focus	true

bspc config external_rules_command $HOME/.config/bspwm/external_rules

source "$HOME/.start-bspwm"


## My Colours ##
bspc config active_border_color	 	$(xrdb -get theme.background)
bspc config focused_border_color 	$(xrdb -get theme.selected)
bspc config normal_border_color		$(xrdb -get theme.background)
bspc config presel_border_color		$(xrdb -get theme.primary)
bspc config urgent_border_color		$(xrdb -get theme.danger)

